---
REQUEST_TESTING_PHRASE: "abc123"
WHITE_LIST_PHRASE: "abc123"
OK_PHRASE: "abc123"
RETEST_PHRASE: "abc123"
BLACKLIST_AUTHORS: "abc123"
SKIP_PHRASE: "abc123"
CRON_SCHEDULE: "* * * *"
USE_COMMENTS: "abc123"
MANAGE_WEBHOOKS: 
ADMIN_LIST:
  - "naveen9devops"
UNSTABLE_AS: pending
AUTO_CLOSE_FAILED_PRS: "abc123"
DISPLAY_ERRORS_DOWNSTREAM: "abc123"
BLACK_LIST_LABELS:
WHITE_LIST_LABELS:
SHARED_SECRET:
SERVER_API_URL:
CREDENTIALS_ID:
CANCEL_BUILD_ON_UPDATE:
SIMPLE_STATUS:
PUBLISH_JENKINS_URL:
  - "https://192.168.0.101:8080/"
BUILD_LOG_LINES_TO_DISPLAY:
  - 15
RESULT_MESSAGES:
STATUS:
MESSAGE:
  - Hi